#!/bin/bash

RESOURCE_GROUP="myResourceGroup"
LOCATION="southeastasia"
VM_NAME="myVM"

az storage blob upload \
  --account-name <storage-account-name> \
  --container-name scripts \
  --file ./path/to/base.ps1 \
  --name base.ps1
