name: Azure DSC Windows Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Azure Terraform Create"]
    types:
      - completed

jobs:
  deploy_windows_dsc:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download JSON Inventory
        uses: actions/download-artifact@v4
        with:
          name: server-inventory
          path: .

      - name: Apply DSC Configuration
        shell: pwsh
        run: |
          $inventory = Get-Content inventory.json | ConvertFrom-Json
          $windowsHosts = $inventory.all.children.windows.hosts

          foreach ($host in $windowsHosts.PSObject.Properties) {
              $hostname = $host.Name
              $hostDetails = $host.Value
              $ip = $hostDetails.ansible_host
              Write-Host "Deploying DSC to $hostname ($ip)"

              # Copy DSC script from repo to remote server
              Write-Host "Copying DSC script to $hostname..."
              Copy-Item -Path dsc/windows_server_dsc.ps1 -Destination "\\$ip\C$\Temp\windows_server_dsc.ps1" -Force

              # Run DSC Configuration remotely
              Invoke-Command -ComputerName $ip -Credential (Get-Credential) -ScriptBlock {
                  param ($dscScript)
                  Write-Host "Applying DSC Configuration..."
                  & "C:\Temp\$dscScript"
              } -ArgumentList "windows_server_dsc.ps1"
          }
