name: Apply Ansible Configuration

on:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Inventory JSON from Cache
        uses: actions/cache@v3
        with:
          path: inventory.json
          key: server-inventory-latest

      - name: Extract Linux Hosts from Inventory JSON
        run: |
          jq '.all.children.linux' inventory.json > linux_inventory.json
          cat linux_inventory.json | jq '.'
      
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook on Remote Hosts
        run: |
          ansible-playbook -i linux_inventory.json ansible/configure-linux.yml
