name: Terraform Destroy for Azure

on:
  schedule:
    - cron: "0 18 * * *" # Runs every Sunday at midnight UTC
  workflow_dispatch: # Manual trigger

permissions:
      id-token: write
      contents: read

env:
      TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_root_certificate_data: ${{ vars.root_certificate_data }}

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Azure credentials
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    # Step 3: Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0 

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    - name: Pull Current State 
      run: terraform refresh

    # Step 5: Plan Terraform Destroy
    - name: Terraform Plan Destroy
      run: terraform plan -destroy -out=destroy.plan

    # Step 6: Apply Terraform Destroy
    - name: Terraform Apply Destroy
      run: terraform apply -auto-approve destroy.plan
