name: Apply DSC Configuration

on:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed

jobs:
  dsc:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Inventory JSON from Cache
        uses: actions/cache@v3
        with:
          path: inventory.json
          key: server-inventory-latest

      - name: Convert JSON to PowerShell Object
        run: |
          $inventory = Get-Content -Path inventory.json | ConvertFrom-Json
          $windowsHosts = $inventory.all.children.windows.hosts
          Write-Output "Windows Hosts: $windowsHosts"
        shell: powershell

      - name: Apply DSC Configuration
        run: |
          Start-DscConfiguration -Path .\DSC -Wait -Force -Verbose
        shell: powershell
