name: Azure DSC Windows Deployment

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Azure Terraform Create"]
    types:
      - completed

jobs:
  deploy_windows_dsc:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download JSON Inventory
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory
          path: .

      - name: Apply DSC Configuration
        shell: pwsh
        run: |
          $inventory = Get-Content inventory.json | ConvertFrom-Json
          $windowsHosts = $inventory.all.children.windows.hosts

          foreach ($host in $windowsHosts.PSObject.Properties) {
              $hostname = $host.Name
              $hostDetails = $host.Value
              $ip = $hostDetails.ansible_host
              Write-Host "Applying DSC Configuration on $hostname ($ip)"

              Invoke-Command -ComputerName $ip -Credential (Get-Credential) -ScriptBlock {
                  Write-Host "Applying DSC..."
                  Start-DscConfiguration -Path "C:\DSCConfigs" -Wait -Verbose -Force
              }
          }
