name: Terraform Destroy for Azure

on:
  schedule:
    - cron: "0 18 * * *" # Runs every Sunday at midnight UTC
  workflow_dispatch: # Manual trigger

permissions:
      id-token: write
      contents: read

      env:
        TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_local_windows_user: ${{ secrets.LOCAL_WINDOWS_USER }}
        TF_VAR_local_windows_password: ${{ secrets.LOCAL_WINDOWS_PASSWORD }}
        TF_VAR_root_certificate_data: ${{ vars.root_certificate_data }}

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0 

    - name: Terraform Init
      run: terraform init

    - name: Pull Current State 
      run: terraform refresh

    - name: Terraform Plan Destroy
      run: terraform plan -destroy -out=destroy.plan

    - name: Terraform Apply Destroy
      run: terraform apply -auto-approve destroy.plan
