name: Apply Ansible Configuration

on:
  workflow_run:
    workflows: ["Inspect Terraform Inventory"]  # Ensures inspection passes first
    types:
      - completed

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Inventory JSON
        uses: actions/download-artifact@v4
        with:
          name: server-inventory
          path: .

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.json configure-linux.yml
