name: Apply Ansible Configuration

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Azure Terraform Create"]
    types:
      - completed

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Inventory JSON
        uses: actions/download-artifact@v4
        with:
          name: inventory
    
      - name: Verify Inventory JSON
        run: cat inventory.json  # Debugging step
      
      - name: Verify Inventory JSON File Exists
        run: |
          if [ ! -f inventory.json ]; then
            echo "Error: inventory.json not found!"
            exit 1
          else
            echo "inventory.json found:"
            cat inventory.json
          fi
  
      - name: Extract Linux Hosts from Inventory JSON
        run: |
          jq '.all.children.linux' inventory.json > linux_inventory.json
          cat linux_inventory.json | jq '.'

      - name: Setup SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $(jq -r 'keys[]' linux_inventory.json) >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook on Remote Hosts
        run: |
          ansible-playbook -i linux_inventory.json -u azureuser --private-key ~/.ssh/id_rsa ansible/configure-linux.yml
