name: Azure Testing Pipeline

on:
  workflow_dispatch:

  permissions:
      id-token: write
      contents: read

jobs:
  inspect_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download Inventory JSON
        uses: actions/download-artifact@v4
        with:
          name: server-inventory
          path: .

      - name: Check if Inventory Exists
        run: |
          if [ ! -f inventory.json ]; then
            echo "❌ inventory.json not found!"
            exit 1
          else
            echo "✅ inventory.json found."
          fi

      - name: Print Inventory JSON
        run: |
          echo "===== inventory.json CONTENTS ====="
          cat inventory.json | jq '.'

      - name: Validate JSON Structure
        run: jq empty inventory.json


