name: Deploy DSC to Windows Server

on:
  workflow_dispatch

#env:
#  DSC_FOLDER: "${{ github.workspace }}\DSC"

jobs:
  deploy-dsc:
    runs-on: windows-latest

    steps:
    # Checkout the repository to access the DSC files
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Terraform Server Names Artifact
      uses: actions/download-artifact@v3
      with:
        name: terraform-outputs

    - name: Extract Terraform names from JSON
      id: parse_servers
      run: |
        server_names=$(jq -r '.server_names.value[]' terraform_outputs.json)
        echo "SERVERS=$server_names" >> $GITHUB_ENV

    # Install PowerShell modules required for DSC
    - name: Install PowerShell DSC Module
      run: |
        Install-Module -Name PSDesiredStateConfiguration -Force -Scope CurrentUser
        Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

    # Deploy DSC to Windows Server
    - name: Apply DSC Configuration
    uses: appleboy/ssh-action@v0.1.5
    with:
      host: ${{ env.SERVERS }}
      username: ${{ secrets.WINDOWS_USER }}
      password: ${{ secrets.WINDOWS_PASSWORD }}
      script: |
        powershell -Command "
        Copy-Item -Path ./dsc/active_directory.ps1 -Destination C:\DSC\active_directory.ps1 -Force;
        .\C:\DSC\active_directory.ps1
        Start-DscConfiguration -Path C:\DSC -Wait -Verbose
        "
  
