name: "azure-terraform-demo deployment"
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    env:
      TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_local_windows_user: ${{ secrets.LOCAL_WINDOWS_USER }}
      TF_VAR_local_windows_password: ${{ secrets.LOCAL_WINDOWS_PASSWORD }}
      TF_VAR_root_certificate_data: ${{ vars.root_certificate_data }}

    steps:

      - name: "Checkout"
        uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: "Terraform Format"
        id: fmt
        run: terraform fmt

      - name: "Terraform Init"
        id: init
        run: | 
          terraform init \
          -backend-config="resource_group_name=LabManagement" \
          -backend-config="storage_account_name=labmanagementstorage01" \
          -backend-config="container_name=azure-terraform-demo" \
          -backend-config="key=terraform.tfstate"

      - name: "Terraform Validate"
        id: validate
        run: terraform validate -no-color

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Terraform Plan"
        id: plan
        run: terraform plan -lock=false -no-color

      - name: "Terraform Apply"
        id: apply
        run: | 
          terraform apply -auto-approve -lock=false -no-color

      - name: Save Windows Server Names
        run: terraform output -json windows_server_names > windows_server_names.json
  
      - name: Save Linux Server Names
        run: terraform output -json linux_server_names > linux_server_names.json

      - name: Upload Windows Server Names
        uses: actions/upload-artifact@v4
        with:
          name: windows_server_names
          path: windows_server_names.json
  
      - name: Upload Linux Server Names
        uses: actions/upload-artifact@v4
        with:
          name: linux_server_names
          path: linux_server_names.json