- name: Verify Inventory JSON File Exists

    if [ ! -f inventory.json ]; then
    echo "Error: inventory.json not found!"
    exit 1
  else
    echo "inventory.json found:"
    cat inventory.json
  fi