name: "Azure DSC Deployment"

on:
  workflow_dispatch:

jobs:
  deploy-dsc:
    runs-on: windows-latest

    env:
      local_windows_user: ${{ secrets.local_windows_password}}
      local_windows_password: ${{ secrets.LOCAL_WINDOWS_PASSWORD }}

    steps:
    # Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install PowerShell Modules (if needed)
    - name: Install PowerShell modules
      shell: pwsh  
      run: |
        Install-Module -Name PSWSMan -Force -SkipPublisherCheck
        Install-Module -Name PSDesiredStateConfiguration -Force -SkipPublisherCheck
      

    # Execute the DSC script on the remote server
    - name: Invoke DSC remotely
      run: |
        $vmNames = Get-Content -Path "./windows_server_names.json" | ConvertFrom-Json  
      
        foreach ($vmName in $vmNames) {

        # Test-WSMan -ComputerName $vmName

        $server = $vmName
        $username = ConvertTo-SecureString -String ${{ secrets.local_windows_user }} -AsPlainText -Force
        $password = ConvertTo-SecureString -String ${{ secrets.local_windows_password }} -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($username, $password)

        $dscScriptPath = "${{ github.workspace }}\dsc\windows_server_dsc.ps1"

        Invoke-Command -ComputerName $server -Credential $credential -ScriptBlock {
            param ($dscScriptPath)
            & PowerShell -File $dscScriptPath
        } -ArgumentList $dscScriptPath

        }



      shell: pwsh
